# This is a basic workflow to help you get started with Actions

name: Python application test with Github Actions

runs on: [push]

steps:
- uses: actions/checkout@v2
- name: Set up Pyton 3.8
  uses: actions/setup-python@v1
  with:
    python-version: 3.8
- name: Install dependencies
  run: |
    make install
- name: Lint with pylint
  run: |
    make lint
- name: Test with pytest
  run: |
    make test
- name: Format code
  run: |
    make format
    
